cluster:
  name: dev

ingress:
  host: localhost
  tls:
    enabled: false
    clusterIssuer:
    secretName:

keycloak:
  enabled: true
  image:
    name: quay.io/keycloak/keycloak
    version: 26.2

  postgres:
    image:
      name: ghcr.io/cloudnative-pg/postgresql
      version: 17.6
    replicaCount: 1
    storageSize: 5Gi
    username: keycloak_user
    secret:
      name: keycloak-secret
      usernameKey: username
      passwordKey: password
    backup:
      schedule: "0 0 0 * * *"
      azure:
        storageAccount: eclipsebackuppg
        containerName: tobi
        retentionPolicy: 7d
        compression: gzip
        secret:
          name: azure-secret
          connectionStringKey: connectionString
    restore:
      enabled: true
    customEnvs:

  ingress:
    enabled: true
    path: /iam

  customEnvs:
