{{- if eq .Values.jaeger.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-grafana
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: grafana # Resolves to Grafana .Chart.Name
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
{{- end }}
