{{- if eq .Values.jaeger.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-grafana
spec:
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
{{- end }}
