{{- if eq .Values.core.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-core-secret
spec:
  encryptedData:
    installerToken: {{ .Values.core.encryptedInstallerToken }}
  template:
    metadata:
      name: {{ .Release.Name }}-core-secret
    type: Opaque
{{- end }}