imagePullSecret:
  name: ghcr-secret

ingress:
  enabled: false
  host:
  path: /eddie
  tls:
    enabled: false
    clusterIssuer:
    secretName:

core:
  version: nightly-20260217
  enabled: true
  secret:
    name: eddie-core-secret
    jwtHmacSecretKey: jwtHmacSecret
    kafkaJaasConfigKey: kafkaJaasConfig

  management:
    url:
    server:
      urlPrefix:

postgres:
  enabled: true
  image:
    name: ghcr.io/cloudnative-pg/postgresql
    version: 17.6
  replicaCount: 1
  storageSize: 5Gi
  username: eddie_user
  databaseName: eddie
  secret:
    name: eddie-postgres-secret
    usernameKey: username
    passwordKey: password
  objectStore:
    enabled: true
  backup:
    enabled: true
    schedule: "0 0 0 * * *"
    retentionPolicy: 7d
    compression: gzip
  azure:
    secret:
      name: azure-secret
      connectionStringKey: connectionString
  customEnvs:


regionConnectors:
  atEda:
    enabled: true
    eligiblePartyId:
    pontonMessenger:
      adapter:
        id:
        version:
      hostname:
      apiEndpoint:
      port:
      folder:
    pontonVolume:
      storageSize: 5Gi

  simulation:
    enabled: true

kafka:
  image:
    name: docker.io/apache/kafka
    version: 4.1.0
  storageSize: 5Gi
  enabled: true
  externalPort: 9095
  secret:
    name: eddie-kafka-secret
    keystoreKey: kafka.keystore.jks
    keystorePasswordKey: keystorePassword
    truststoreKey: kafka.truststore.jks
    truststorePasswordKey: truststorePassword
    superUsersKey: superUsers
    adminPasswordKey: adminPassword
    jaasConfigKey: kafka_server_jaas.conf
    clientPropertiesKey: client.properties
  acls:
    create: true
    users:
    - name: eddie
      consumeTopics:
        - name: "fw.eclipse-prod"
          group: "*"
        - name: "ep.eclipse-prod"
          group: "*"
      produceTopics:
        - name: "fw.eclipse-prod"
        - name: "ep.eclipse-prod"

outboundConnectors:
  kafka:
    enabled: true
    format: xml
    eddieId:

  adminConsole:
    enabled: false

cluster:
  name: dev