{{- if eq .Values.kafka.enabled true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kafka-pvc
  {{- include "eddie.kafka.labels" . | indent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.storageSize }}
{{- end }}
