cluster:
  name: dev

imagePullSecret:
  name: ghcr-secret

core:
  image:
    name: ghcr.io/eclipse-energy/federator
    version: latest
  replicaCount: 1
  keysSecret:
    name: federator-keys-secret
  keycloak:
    uri:
    realm:

ingress:
  enabled: false
  host:
  path: /federator
  tls:
    enabled: false
    clusterIssuer:
    secretName:

postgres:
  replicaCount: 1
  username: federator_user
  secret:
    name: postgres-secret
    usernameKey: username
    passwordKey: password
  image:
    name: ghcr.io/cloudnative-pg/postgresql
    version: 17.6
  storageSize: 5Gi
  backup:
    schedule: "0 0 0 * * *"
    azure:
      retentionPolicy: 7d
      compression: gzip
      secret:
        name: azure-secret
        connectionStringKey: connectionString
  customEnvs:
