cluster:
  name: dev

keycloak:
  enabled: true
  image:
    name: quay.io/keycloak/keycloak
    version: 26.2

  postgres:
    image:
      name: ghcr.io/cloudnative-pg/postgresql
      version: 17.6
    replicaCount: 1
    storageSize: 5Gi
    username: keycloak_user
    secret:
      name: keycloak-secret
      usernameKey: username
      passwordKey: password
    backup:
      schedule: "0 0 0 * * *"
      azure:
        retentionPolicy: 7d
        compression: gzip
        secret:
          name: azure-secret
          connectionStringKey: connectionString
    customEnvs:

  ingress:
    enabled: true
    path: /iam

  customEnvs:

jaeger:
  enabled: true
  image:
    name: jaegertracing/all-in-one
    version: 1.69.0

  ingress:
    basicAuth:
      enabled: false
      secret:
        name: jaeger-auth
    enabled: false
    path: /jaeger

ingress:
  host:
  tls:
    enabled: false
    clusterIssuer:
    secretName:

grafana:
  enabled: true

  customIngress:
    enabled: false
    path: /grafana

  service:
    enabled: false

  persistence:
    enabled: true

  testFramework:
    enabled: false

  rbac:
    create: false

  serviceAccount:
    create: false
