cluster:
  name: dev

keycloak:
  enabled: true
  image:
    name: quay.io/keycloak/keycloak
    version: 26.2

  postgres:
    image:
      name: ghcr.io/cloudnative-pg/postgresql
      version: 17.6
    replicaCount: 1
    storageSize: 5Gi
    username: keycloak_user
    secret:
      name: keycloak-secret
      usernameKey: username
      passwordKey: password
    backup:
      schedule: "0 0 0 * * *"
      azure:
        retentionPolicy: 7d
        compression: gzip
        secret:
          name: azure-secret
          connectionStringKey: connectionString
    restore:
      enabled: false
    customEnvs:

  ingress:
    enabled: true
    path: /iam

  customEnvs:

jaeger:
  enabled: true
  image:
    name: jaegertracing/all-in-one
    version: 1.69.0

  ingress:
    basicAuth:
      enabled: false
      secret:
        name: jaeger-auth
    enabled: false
    path: /jaeger

ingress:
  host:
  tls:
    enabled: false
    clusterIssuer:
    secretName:

grafana:
  enabled: true

  customIngress:
    enabled: false
    path: /grafana

  service:
    enabled: false

  persistence:
    enabled: true

  testFramework:
    enabled: false

loki:
  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    pattern_ingester:
        enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    ruler:
      enable_api: true

  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1

  lokiCanary:
    enabled: false

  test:
    enabled: false

  minio:
    enabled: true

  backend:
    replicas: 0

  read:
    replicas: 0

  write:
    replicas: 0

  ingester:
    replicas: 0

  querier:
    replicas: 0

  queryFrontend:
    replicas: 0

  queryScheduler:
    replicas: 0

  distributor:
    replicas: 0

  compactor:
    replicas: 0

  indexGateway:
    replicas: 0

  bloomCompactor:
    replicas: 0

  bloomGateway:
    replicas: 0

promtail:
  enabled: true
