keycloak:
  enabled: true
  image:
    name: quay.io/keycloak/keycloak
    version: 26.2

  secret:
    name: keycloak-secret
    postgres:
      usernameKey: postgres-username
      passwordKey: postgres-password

  postgres:
    image:
      name: postgres
      version: 17.6
    storageSize: 5Gi
    customEnvs:

  ingress:
    enabled: true
    path: /iam

  customEnvs:

jaeger:
  enabled: true
  image:
    name: jaegertracing/all-in-one
    version: 1.69.0

  ingress:
    basicAuth:
      enabled: false
      secret:
        name: jaeger-auth
    enabled: false
    path: /jaeger

ingress:
  host:
  tls:
    enabled: false
    clusterIssuer:
    secretName:
