{{- if eq .Values.timescaledb.enabled true }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-timescaledb
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  instances: {{ .Values.timescaledb.instances }}
  imageName: {{ .Values.timescaledb.image.name }}:{{ .Values.timescaledb.image.version }}

  postgresql:
    shared_preload_libraries:
      - timescaledb

  bootstrap:
    {{- if eq .Values.timescaledb.bootstrapMode "initdb" }}
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
        - ALTER ROLE "{{ .Values.timescaledb.username }}" WITH CREATEROLE;
    {{- end }}
    {{- if eq .Values.timescaledb.bootstrapMode "recoverObjectStore" }}
    recovery:
      source: recoverySource
    {{- end }}
      database: {{ .Values.timescaledb.database }}
      owner: {{ .Values.timescaledb.owner }}
      secret:
        name: {{ .Values.timescaledb.secret.name }}
  storage:
    size: {{ .Values.timescaledb.storageSize }}

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ $.Release.Name }}-timescaledb

  {{- if eq .Values.timescaledb.bootstrapMode "recoverObjectStore" }}
  externalClusters:
    - name: recoverySource
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ .Release.Name }}-timescaledb-recover
  {{- end }}
{{- end }}
