{{- if eq .Values.timescaledb.enabled true }}
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: {{ .Release.Name }}-timescaledb
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  images:
    - major: {{ .Values.timescaledb.image.majorVersion }}
      image: {{ .Values.timescaledb.image.name }}:{{ .Values.timescaledb.image.version }}
{{- end }}