{{- if eq .Values.timescaledb.enabled true }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Release.Name }}-timescaledb-azure
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  retentionPolicy: {{ .Values.timescaledb.backup.azure.retentionPolicy }}
  configuration:
    destinationPath: azure://{{ .Values.cluster.name }}/{{ .Release.Name }}/timescaledb
    azureCredentials:
      connectionString:
        name: {{ .Values.timescaledb.backup.azure.secret.name }}
        key: {{ .Values.timescaledb.backup.azure.secret.connectionStringKey }}
    wal:
      compression: {{ .Values.timescaledb.backup.azure.compression }}
{{- end }}