{{- if eq .Values.timescaledb.enabled true }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Release.Name }}-timescaledb
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  retentionPolicy: {{ .Values.timescaledb.objectStore.retentionPolicy }}
  configuration:
    destinationPath: {{ include "eclipse-backend.timescaledb.object-store.destination-path" .Values.timescaledb.objectStore }}
    azureCredentials:
      connectionString:
        name: {{ .Values.timescaledb.objectStore.azureSecret.name }}
        key: {{ .Values.timescaledb.objectStore.azureSecret.connectionStringKey }}
    wal:
      compression: {{ .Values.timescaledb.objectStore.compression }}
---
{{- if eq .Values.timescaledb.bootstrapMode "recoverObjectStore" }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Release.Name }}-timescaledb-recover
  {{- include "eclipse-backend.timescaledb.labels" . | indent 2 }}
spec:
  retentionPolicy: {{ .Values.timescaledb.recoveryObjectStore.retentionPolicy }}
  configuration:
    destinationPath: {{ include "eclipse-backend.timescaledb.object-store.destination-path" .Values.timescaledb.recoveryObjectStore }}
    azureCredentials:
      connectionString:
        name: {{ .Values.timescaledb.recoveryObjectStore.azureSecret.name }}
        key: {{ .Values.timescaledb.recoveryObjectStore.azureSecret.connectionStringKey }}
    wal:
      compression: {{ .Values.timescaledb.recoveryObjectStore.compression }}
---
{{- end }}
{{- end }}
