security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='admin' password='admin';
ssl.truststore.password=eddie2024
ssl.truststore.location=/home/benjamin/repos/eclipse-base-helm/charts/eddie/temp/root-ca-truststore.jks
