{{- if .Values.keycloak.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-keycloak-postgres
  {{- include "eclipse-shared.keycloak.labels" . | indent 2 }}
spec:
  instances: {{ .Values.keycloak.postgres.replicaCount }}
  imageName: {{ .Values.keycloak.postgres.image.name }}:{{ .Values.keycloak.postgres.image.version }}

  {{- if .Values.keycloak.postgres.restore.enabled }}
  bootstrap:
    recovery:
      source: keycloak-recovery-source
  {{- else }}
  bootstrap:
    initdb:
      database: keycloak
      owner: {{ .Values.keycloak.postgres.username }}
      secret:
        name: {{ .Values.keycloak.postgres.secret.name }}
  {{- end }}

  storage:
    size: {{ .Values.keycloak.postgres.storageSize }}

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ .Release.Name }}-keycloak-postgres-azure-new

  externalClusters:
    - name: keycloak-recovery-source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ .Release.Name }}-keycloak-postgres-azure
{{- end }}