{{- if eq .Values.core.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-core
  {{- include "eddie.core.labels" . | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-core
  template:
    metadata:
    {{- include "eddie.core.labels" . | indent 6 }}
    spec:
      containers:
        - name: eddie-core
          image: "ghcr.io/eddie-energy/eddie:{{ .Values.core.version }}"
          ports:
            - containerPort: 8080
              name: api
            - containerPort: 9090
              name: management
          env:
            - name: EDDIE_PUBLIC_URL
              value: "{{ if eq .Values.ingress.tls.enabled true }}https{{ else }}http{{ end }}://{{ .Values.ingress.host }}{{ .Values.ingress.path }}"
            - name: EDDIE_JWT_HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.core.secret.name }}
                  key: {{ .Values.core.secret.jwtHmacSecretKey }}
            - name: EDDIE_DATA_NEEDS_CONFIG_DATA_NEED_SOURCE
              value: "DATABASE"
            - name: SPRING_DATASOURCE_URL
              value: {{ include "eddie.postgres-url" . }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.usernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.passwordKey }}
            - name: EDDIE_MANAGEMENT_URL
              value: {{ .Values.core.management.url }}
            - name: EDDIE_MANAGEMENT_SERVER_PORT # In Kubernetes there is no point in making this configurable since there will be no local port collisions
              value: "9090"
            {{- include "eddie.region-connectors.at-eda.envs" . | indent 12 }}
            {{- include "eddie.outbound-connectors.admin-console.envs" . | indent 12 }}
            {{- include "eddie.outbound-connectors.kafka.envs" . | indent 12 }}
            - name: REGION_CONNECTOR_SIM_ENABLED
              value: {{ .Values.regionConnectors.simulation.enabled | quote }}
            {{- include "eddie.extraEnv" .Values.core.extraEnv | indent 12 }}
          {{- if eq .Values.regionConnectors.atEda.enabled true }}
          volumeMounts:
            - name: ponton
              mountPath: /opt/ponton
          {{- end }}

      {{- if eq .Values.regionConnectors.atEda.enabled true }}
      volumes:
        - name: ponton
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-core-ponton-pvc
      {{- end }}

      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
{{- end }}