{{- if and (eq .Values.postgres.enabled true) (eq .Values.postgres.backup.enabled true) }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Release.Name }}-postgres
  {{- include "federator.postgres.labels" . | indent 2 }}
spec:
  cluster:
    name: {{ .Release.Name }}-postgres
  immediate: true
  schedule: {{ .Values.postgres.backup.schedule }}
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: {{ .Release.Name }}-postgres
{{- end }}
