{{- if and (eq .Values.keycloak.enabled true) (eq .Values.keycloak.postgres.enabled true) }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-keycloak-postgres
  {{- include "eclipse-shared.keycloak.labels" . | indent 2 }}
spec:
  instances: {{ .Values.keycloak.postgres.instances }}
  imageName: {{ .Values.keycloak.postgres.image.name }}:{{ .Values.keycloak.postgres.image.version }}
  bootstrap:
    {{- if eq .Values.keycloak.postgres.bootstrapMode "initdb" }}
    initdb:
    {{- end }}
    {{- if eq .Values.keycloak.postgres.bootstrapMode "recoverObjectStore" }}
    recovery:
      source: recoverySource
    {{- end }}
      database: {{ .Values.keycloak.postgres.database }}
      owner: {{ .Values.keycloak.postgres.owner }}
      secret:
        name: {{ .Values.keycloak.postgres.secret.name }}
  storage:
    size: {{ .Values.keycloak.postgres.storageSize }}

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ $.Release.Name }}-keycloak-postgres

  {{- if eq .Values.keycloak.postgres.bootstrapMode "recoverObjectStore" }}
  externalClusters:
    - name: recoverySource
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ .Release.Name }}-keycloak-postgres-recover
  {{- end }}
{{- end }}
