{{- if eq .Values.matter.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matter
spec:
  selector:
    app: {{ .Release.Name }}-matter
  ports:
    - name: matter-server
      port: {{ .Values.matter.server.ports.ws }}
      targetPort: matter-server
    - name: matter-bridge
      port: {{ .Values.matter.bridge.ports.http }}
      targetPort: matter-bridge
{{- end }}